project:
  type: website
  output-dir: docs

website:
  title: "James Salamon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: James Salamon_Resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
  page-footer:
    center: |
      Â© 2025 James Salamon
      _Last updated: July 5, 2025_
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true